### ISSUE TITLE
Question: will parallelization be supported/is parallel development underway?

### ISSUE THREAD

**Issue by wyattmcdonnell** [KrishnaswamyLab/MAGIC#100]
Hi there!

Thanks so much for putting MAGIC together! It's proving to be a very interesting and powerful tool on some of our scRNAseq data. 

As you can imagine, for very large datasets, imputation will be increasingly important but also time-consuming to run single-threaded. Is your team working on parallelizing MAGIC? If not, would love to work with you on getting this going, and if so, happy to help test and try and break a development version!

Best wishes,
Wyatt

**Comment by dvdijk** [comment]
Hi Wyatt,

We're working on a fast and scalable version of MAGIC. We'll put it on github soon.

David

**Comment by danieldager** [comment]
Hi Wyatt, 

MAGIC v1.0, released a few days ago, supports parallelization. Uninstall your current version of MAGIC and reinstall per the directions of the new README. Then, when creating the MAGIC operator, you can specify the number of CPUs to be used in computation:  

`magic_op = magic.MAGIC(n_jobs=x)`

Where "x" is the number of CPU's (If -1, all available CPUs are used). 

I'm closing this for now, but please feel free to open a new issue if you still have problems!

Best,
Daniel
