### ISSUE TITLE
Error during Rescaling

### ISSUE THREAD

**Issue by JurijsNazarovs** [KrishnaswamyLab/MAGIC#103]
Hello, I have a following error in the last step.

[1] "Rescaling"
Error in quantile.default(x, rescale_percent) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
Calls: run_magic -> apply -> FUN -> quantile -> quantile.default
Execution halted

**Comment by JurijsNazarovs** [comment]
I have not got a support regarding this issue. I ended up with using Python version of a method. There is no such problem.

**Comment by dvdijk** [comment]
We released a new version of MAGIC that shouldn't have this problem.

**Comment by alextamburino** [comment]
Ok, thanks. I just installed the R version this week. Perhaps I can check
for a newer version.

**Comment by dvdijk** [comment]
yeah, the new version was released yesterday. Its much more scalable and
much faster now.

**Comment by alextamburino** [comment]
That's great! Thanks!!
