### ISSUE TITLE
'problem too large' error 

### ISSUE THREAD

**Issue by lzj1769** [KrishnaswamyLab/MAGIC#105]
Hi,

I run MAGIC successfully on a small dataset, but when I try to use it on a large dataset, I got the error:

 Warning message:
 package ‘Matrix’ was built under R version 3.4.4
 Warning message:
 package ‘Rmagic’ was built under R version 3.4.3
 Error in asMethod(object) :
    Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
    Calls: run_magic ... as.matrix -> as.matrix.Matrix -> as -> asMethod -> .Call
 Execution halted

**Comment by chlee-tabin** [comment]
Sometimes I had issues similar to this when the row and column was transposed (it is different from some popular scRNAseq defaults).

**Comment by danieldager** [comment]
Hi all,

There's a good chance that these problems were resolved with the release of MAGIC v1.0. Uninstall your current version of MAGIC and reinstall per the directions of the new README. I'm closing this for now; please feel free to open a new issue if you still have problems!
