### ISSUE TITLE
magic() documentation in R

### ISSUE THREAD

**Issue by ronammar** [KrishnaswamyLab/MAGIC#119]
In `Rmagic::magic()` the documentation reports that the default number of principal components is 20, but the default in `magic()` is set to 100.

**Comment by ronammar** [comment]
Great - thanks! I figured it doesn't really matter based on your published methods:

> We also note that MAGIC is relatively robust to the number of principle components selected, within a reasonable range

But would remove ambiguity as to what the default should be.

**Comment by scottgigante** [comment]
Thanks again! The fix has been added to the development branch and will be included in the next release.
