### ISSUE TITLE
Logging error in Rmagic on Windows

### ISSUE THREAD

**Issue by b-dawes** [KrishnaswamyLab/MAGIC#120]
Hello,

I've been trying to run magic in R for easier compatibility with the seurat library. I'm able to run magic and get results, however there is an issue with the logging.  Everytime something is logged, I get an error message followed by the actual message. For example, here's the last part of the log:

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\bdawes\AppData\Local\CONTIN~1\ANACON~1\envs\python3\lib\logging\__init__.py", line 983, in emit
    stream.write(msg)
  File "C:\Users\bdawes\AppData\Local\CONTIN~1\ANACON~1\envs\python3\lib\site-packages\magic\logging.py", line 30, in write_r_safe
    os.write(1, bytes(msg, 'utf8'))
OSError: [Errno 9] Bad file descriptor
Call stack:
  File "C:\Users\bdawes\AppData\Local\CONTIN~1\ANACON~1\envs\python3\lib\site-packages\magic\magic.py", line 531, in fit_transform
    logging.log_complete('MAGIC')
  File "C:\Users\bdawes\AppData\Local\CONTIN~1\ANACON~1\envs\python3\lib\site-packages\magic\logging.py", line 129, in log_complete
    get_task_logger().complete_task(name)
  File "C:\Users\bdawes\AppData\Local\CONTIN~1\ANACON~1\envs\python3\lib\site-packages\magic\logging.py", line 62, in complete_task
    name, runtime))
  File "C:\Users\bdawes\AppData\Local\CONTIN~1\ANACON~1\envs\python3\lib\site-packages\magic\logging.py", line 51, in log
    self.logger.info(msg)
Message: 'Calculated MAGIC in 3.89 seconds.'
Arguments: ()
```

I would assume this is probably caused either by running on Windows or running in R. For reference, I'm using R 3.4.1, python 3.5.3, and Windows 7. Let me know if there's any further info you need.

Best,
Brian

**Comment by scottgigante** [comment]
Hi Brian,

This is rather odd - I have tested this with Python 3.5, R 3.4 and Windows 10 and it works fine, but perhaps Windows 10 interacts with Python differently. I can add in a workaround in the Python logging module to catch this exception, but the result might be that MAGIC won't print output to the R console. Is that acceptable for you?

Thanks very much for the report.

Best,
Scott

**Comment by scottgigante** [comment]
@b-dawes if you could please try out the new fix by running
```
pip install --user git+git://github.com/KrishnaswamyLab/MAGIC.git@windows7_logging#subdirectory=python
```
and let me know what happens when you run `Rmagic`, that would be much appreciated.

**Comment by b-dawes** [comment]
Thanks for the quick response Scott!

This isn't a huge issue for me as it still runs and outputs the messages, I mostly just wanted to let you guys know about it. One thing that I noticed might be missing if messages aren't printed is the optimal value of t when running with t=auto. I looked around in the $operator slot for this and wasn't able to find it there (let me know if it is in there somewhere and I just missed it).

I'll try the patched version and let you know the results.

**Comment by b-dawes** [comment]
Also my py_config:

```
python:         C:\Users\bdawes\AppData\Local\Continuum\Anaconda2\envs\python3\python.exe
libpython:      C:/Users/bdawes/AppData/Local/Continuum/Anaconda2/envs/python3/python35.dll
pythonhome:     C:\Users\bdawes\AppData\Local\CONTIN~1\ANACON~1\envs\python3
version:        3.5.3 | packaged by conda-forge | (default, May 12 2017, 16:16:49) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\bdawes\AppData\Local\CONTIN~1\ANACON~1\envs\python3\lib\site-packages\numpy
numpy_version:  1.14.1
magic:          C:\Users\bdawes\AppData\Local\CONTIN~1\ANACON~1\envs\python3\lib\site-packages\magic\__init__.p

python versions found: 
 C:\Users\bdawes\AppData\Local\CONTIN~1\ANACON~1\python.exe
 C:\Users\bdawes\AppData\Local\Continuum\Anaconda2\envs\python3\python.exe
```

**Comment by scottgigante** [comment]
My apologies, this is my fault for having identical logging modules in both graphtools and MAGIC. You'll need to also install
```
pip install --user git+git://github.com/KrishnaswamyLab/graphtools.git@windows7_logging
```
Hopefully that resolves the problem. I'll also fix the change to logging which is now returning double whitespace.

**Comment by b-dawes** [comment]
Thanks Scott. I had to pip uninstall graphtools before installing the patched version, but it is now working fine. Also the extra whitespace is gone too. My output:

```
Calculating MAGIC...
Calculating graph and diffusion operator...
Calculating PCA...
Calculated PCA in 1.81 seconds.
Calculating KNN search...
Calculated KNN search in 0.23 seconds.
Calculating affinities...
Calculated affinities in 0.70 seconds.
Calculated graph and diffusion operator in 2.82 seconds.
Calculating imputation...
Automatically selected t = 12
Calculated imputation in 0.59 seconds.
Calculated MAGIC in 3.63 seconds.
```

Thanks again,
Brian

**Comment by scottgigante** [comment]
Thanks Brian for the confirmation. This fix is now on the `dev` branch and will be a part of the next release.
