### ISSUE TITLE
magic module not found from knitr

### ISSUE THREAD

**Issue by ronammar** [KrishnaswamyLab/MAGIC#121]
When I have the following Rmarkdown script:

```Rmd
---
title: "Untitled"
output: html_document
---

```{r}
library(Rmagic)
library(reticulate)

print(py_config())
print(py_module_available("scipy"))
print(py_module_available("magic"))
print(py_available())
print(py_numpy_available())
#```
```

`reticulate` is unable to detect the magic module. However, if I run this code interactively, the module is found. Any idea what could be going wrong?

Thanks!

**Comment by scottgigante** [comment]
Hi @ronammar , I think I'm going to defer to https://github.com/rstudio/reticulate on this one - unfortunately I don't think this is an issue I can solve from the MAGIC codebase.

**Comment by ronammar** [comment]
Thanks for the quick reply.
Does reticulate only work from within RStudio? From the command line console I can't seem to get Rmagic working either.

For example, the following commands on the R console on the command line produce an error:

```r
library(Rmagic)
magic(magic_testdata)
```

```
Error in install.magic() : 
  Cannot install MAGIC, please install from a console with pip install --user git+git://github.com/KrishnaswamyLab/MAGIC.git#subdirectory=python
```

These 2 lines work fine within an RStudio console.

**Comment by scottgigante** [comment]
It runs for me - is it possible that your `py_config` is different in the console compared to in RStudio? You could try setting the `RETICULATE_PYTHON` environment variable and see if that changes things.

**Comment by ronammar** [comment]
Thanks - I'll explore this option.

**Comment by ronammar** [comment]
Solved: For posterity, if anyone else is experiencing knitr/console issues on mac os, this solution worked for me: https://stackoverflow.com/a/33873802/2776559

**Comment by scottgigante** [comment]
Wow. Congratulations on some impressive detective work! Thanks for posting the solution.
