### ISSUE TITLE
Error for loading EMT_example

### ISSUE THREAD

**Issue by k326xh** [KrishnaswamyLab/MAGIC#127]
Hi,

The 2nd Rmarkdown tutorial link (http://htmlpreview.github.io/?https://github.com/KrishnaswamyLab/MAGIC/blob/master/Rmagic/inst/examples/EMT_tutorial.hmtl) may be broken. It shows: 
> Error: Cannot load file https://raw.githubusercontent.com/KrishnaswamyLab/MAGIC/master/Rmagic/inst/examples/EMT_tutorial.hmtl

**Comment by scottgigante** [comment]
Hi @k326xh , 

Thanks for the report! There is a typo in the link: you can find the tutorial at http://htmlpreview.github.io/?https://github.com/KrishnaswamyLab/MAGIC/blob/master/Rmagic/inst/examples/EMT_tutorial.html

I'll fix this error as soon as possible. Thanks for letting us know!
