### ISSUE TITLE
10x data with R version

### ISSUE THREAD

**Issue by ewitt1093** [KrishnaswamyLab/MAGIC#129]
Hello,
I see that you have a way to load 10X data with the Matlab version of MAGIC.  Do you have a similar function in the R version?  I'm a little stuck trying to convert my 10X data to a form MAGIC can handle.

Thanks!

**Comment by scottgigante** [comment]
Hi @ewitt1093 ,

You can find an equivalent function in R using Seurat: https://rdrr.io/github/satijalab/seurat/man/Read10X.html

You can run MAGIC on a Seurat object as detailed here: https://github.com/satijalab/seurat/issues/612#issuecomment-404524849

Good luck and don't hesitate to open another issue if you run into problems running MAGIC.

**Comment by igordot** [comment]
That's much more convenient!

I noticed that for the Seurat object, you use the `data` slot, which is log-transformed by default. However, in the MAGIC vignette, you mention:
> We should library size normalize and transform the data prior to MAGIC. Many people use a log transform, which requires adding a “pseudocount” to avoid log(0). We square root instead, which has a similar form but doesn’t suffer from instabilities at zero.

Does it not make a significant difference whether it's log or square-root-transformed? Or is the assumption just that the normalization performed by Seurat is the most optimal one?

**Comment by scottgigante** [comment]
MAGIC will work with any sublinear transformation. We prefer the square root as we find it gives better results, but given you're operating in the Seurat ecosystem I think it's easier to let you use whatever transformation Seurat provides. Users who wish to try analysis not offered by Seurat can always pull their data out of Seurat and apply MAGIC to the matrix itself.
