### ISSUE TITLE
Rmagic error :Error in pymagic$MAGIC

### ISSUE THREAD

**Issue by verma014** [KrishnaswamyLab/MAGIC#130]
Hi,
I get the following error when I run Rmagic using the example data.

> data(magic_testdata)
> MAGIC_data <- magic(magic_testdata, genes=c("VIM", "CDH1", "ZEB1"))
Error in pymagic$MAGIC(k = k, a = alpha, t = t, n_pca = npca, knn_dist = knn.dist.method,  : 
  attempt to apply non-function

I confirmed the following -

> reticulate::py_module_available("magic")
[1] TRUE
> reticulate::py_available() 
[1] TRUE
> reticulate::import("magic") 
Module(magic)

Any thoughts?

**Comment by scottgigante** [comment]
Hi @verma014 ,

Thanks for getting in touch! It looks like you might have an old version of the MAGIC python package installed. Can you please run in a terminal:
```
pip uninstall magic
pip install --user magic-impute
```
and let me know if the issue is fixed? Thanks!

**Comment by verma014** [comment]
Unfortunately, it did not.
When I do 
>pip uninstall magic
I receive 
>Skipping magic as it is not installed.

I uninstalled magic-impute and reinstalled it. I also tried to remove and do a fresh install of miniconda but still receive the same error. 

> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.10.0.9001 Rmagic_1.0.0           Matrix_1.2-14         

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18     lattice_0.20-35  grid_3.4.4       plyr_1.8.4       jsonlite_1.5    
 [6] gtable_0.2.0     scales_0.5.0     ggplot2_2.2.1    pillar_1.2.2     rlang_0.2.0     
[11] lazyeval_0.2.1   tools_3.4.4      munsell_0.4.3    yaml_2.1.19      compiler_3.4.4  
[16] colorspace_1.3-2 tibble_1.4.2    
>

**Comment by scottgigante** [comment]
Okay, that's odd. Do you mind opening a python interpreter and running the following: (I've included my results for reference)
```
>>> import magic
>>> magic.__version__
'1.2.1'
>>> dir(magic)
['MAGIC', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'absolute_import', 'io', 'magic', 'plot', 'preprocessing', 'utils', 'version']
>>> magic.MAGIC
<class 'magic.magic.MAGIC'>
````
and for good measure, let's try the same thing in R:
```
> pymagic <- reticulate::import("magic")
> pymagic$`__version__`
[1] "1.2.1"
> pymagic$ <and then hit Tab twice quickly>
pymagic$absolute_import  pymagic$magic            pymagic$plot             pymagic$utils
pymagic$io               pymagic$MAGIC            pymagic$preprocessing    pymagic$version
> pymagic$MAGIC
<class 'magic.magic.MAGIC'>
> reticulate::py_config()
python:         /usr/bin/python
libpython:      /usr/lib/libpython3.7m.so
pythonhome:     /usr:/usr
version:        3.7.0 (default, Jul 15 2018, 10:44:58)  [GCC 8.1.1 20180531]
numpy:          /usr/lib/python3.7/site-packages/numpy
numpy_version:  1.15.0

python versions found:
 /usr/bin/python
 /usr/bin/python3
```

**Comment by scottgigante** [comment]
Hi @verma014 ,

That explains things! `reticulate` is not running the `pythonw` interpreter, but instead is running the system python which just happens to have an old version of MAGIC installed. I'll ask you to run in a terminal (again with the expected result shown below):
```
$ which pythonw
/usr/bin/.../python
```
and then with the result of that call,
```
$ echo "export RETICULATE_PYTHON="/usr/bin/.../python" >> ~/.bashrc
$ source ~/.bashrc
```
and then restart R and run
```
> reticulate::py_config()
(hopefully this shows that pythonw is running, and not /usr/local/bin/python3)
> pymagic <- reticulate::import("magic")
> pymagic$MAGIC
<class 'magic.magic.MAGIC'>
```

**Comment by verma014** [comment]
Thanks for your help @scottgigante.
Setting the path did not work, but I was able to find the old version of magic, delete it, reinstall miniconda, magic and Rmagic and it works now!

**Comment by scottgigante** [comment]
No worries, glad it's working!
