### ISSUE TITLE
Available codes to repeat results in Cell paper

### ISSUE THREAD

**Issue by MichaelPeibo** [KrishnaswamyLab/MAGIC#134]
Hi, MAGIC team

Are there codes available to reproduce similar analysis in Cell paper?
I found a [link](http://nbviewer.jupyter.org/github/pkathail/magic/blob/develop/notebooks/Magic_single_cell_RNAseq.ipynb) which seems to be a tutorial, but it reports a 404 error.

**Comment by scottgigante** [comment]
Hi @MichaelPeibo ,

Where was that link? I'll make sure to fix it to point to the right place. 

There are two tutorials shown here: https://github.com/KrishnaswamyLab/MAGIC#tutorials

The EMT tutorial covers initial analysis of the EMT data shown in the paper. @dvdijk might be able to mention whether the full analysis code is available.

**Comment by MichaelPeibo** [comment]
Link I mentioned before is in here https://github.com/dpeerlab/magic

> Interactive command line
A tutorial on MAGIC usage and results visualization for single cell RNA-seq data can be found in this notebook: http://nbviewer.jupyter.org/github/pkathail/magic/blob/develop/notebooks/Magic_single_cell_RNAseq.ipynb

**Comment by dvdijk** [comment]
hi @MichaelPeibo 
Please see our tutorials. Our https://github.com/KrishnaswamyLab/scprep package provides tools for EMD differential expression analysis. For archetypal analysis please look for the PCHA method. I used it in matlab but there should be several packages available in python. Good luck!

**Comment by MichaelPeibo** [comment]
Hi, @dvdijk 

Great! I will check it out.

BTW, nice and MAGIC method!
