### ISSUE TITLE
Question to get the squared exponentiated Markov matrix

### ISSUE THREAD

**Issue by thanhbuu04** [KrishnaswamyLab/MAGIC#136]
Hi, is there any way that I can get the squared Markov exponentiated matrix after I apply magic in R? Thank you.

**Comment by scottgigante** [comment]
Hi @thanhbuu04 , 

We don't store the exponentiated matrix, but you can retrieve it and exponentiate it yourself. It is stored as described below.

```
library(Rmagic)
library(expm)
data <- ...
magic_data <- magic(data)
t <- ... (set according to logging output of MAGIC)
P <- magic_data$operator$diff_op
P_power_t <- P %^% t
```
