### ISSUE TITLE
MELD?

### ISSUE THREAD

**Issue by chlee-tabin** [KrishnaswamyLab/MAGIC#143]
Hi,

I am wondering if there is any plan for a release regarding MELD, which I encountered on one of professor Krishnaswamy's talk, and seems to be an extension(?) of MAGIC concept. Is there some tips of even crudely approach MAGIC code?

**Comment by dburkhardt** [comment]
Sorry for the extra long delay. MELD is now available!

Check out our preprint on BioRxiv: https://www.biorxiv.org/content/10.1101/532846v1

And our GitHub repo: www.github.org/MELD
