### ISSUE TITLE
Got error " ValueError: Input contains NaN, infinity or a value too large for dtype('float64')"

### ISSUE THREAD

**Issue by yongjieliu** [KrishnaswamyLab/MAGIC#144]
Hello,
I got an error when running Rmagic on my own data.

```
>   magic.data <- library.size.normalize(magic.data)
>   magic.data <- sqrt(magic.data)
>   magic.obj <- magic(magic.data)
      Calculating MAGIC...
      Calculating graph and diffusion operator...
      Calculating PCA...
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

Then I  skipped the normalisation step, Rmagic works very well.
```
>   magic.obj <- magic(magic.data)
      Calculating MAGIC...
      Calculating graph and diffusion operator...
      Calculating PCA...
     Calculated PCA in 23.69 seconds.
     Calculating KNN search...
     .....
```

**Comment by scottgigante** [comment]
Hi @yongjieliu, just checking in to see if you worked this out. One possibility I can see is that the median library size is negative, if your data was somehow already normalized. If this happens to somebody else, I would like to have a more informative error message.

**Comment by yongjieliu** [comment]
Hello @scottgigante,
The error was caused by the wrong matrix. My magic.data is  a  [genes X cells] matrix and the inpution of Rmagic should be a [cells X genes] matrix.

**Comment by scottgigante** [comment]
Great, glad you worked it out

**Comment by LiJiaqi96** [comment]
I encountered the same problem. I have transposed the matrix so the number of genes and cells are correct. But still there was RunTime Error
`> embryo <- read.table('counts.txt', header=T, row.names=1)
    magic(t(embryo))
    Calculating MAGIC...
    Running MAGIC on 1529 cells and 26178 genes.
    Calculating graph and diffusion operator...
      Calculating PCA...
      Calculated PCA in 3.59 seconds.
      Calculating KNN search...
      Calculated KNN search in 0.62 seconds.
      Calculating affinities...
      Calculated affinities in 0.21 seconds.
    Calculated graph and diffusion operator in 4.48 seconds.
    Calculating imputation...
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

Detailed traceback: 
  File "/data8t_5/ljq/anaconda3/lib/python3.6/site-packages/magic/magic.py", line 574, in fit_transform
    X_magic = self.transform(**kwargs)
  File "/data8t_5/ljq/anaconda3/lib/python3.6/site-packages/magic/magic.py", line 518, in transform
    plot=plot_optimal_t, ax=ax)
  File "/data8t_5/ljq/anaconda3/lib/python3.6/site-packages/magic/magic.py", line 683, in _impute
    data_imputed = self.diff_op.dot(data_imputed)
  File "/data8t_5/ljq/anaconda3/lib/python3.6/site-packages/magic/magic.py", line 160, in diff_op
    return self.graph.diff_op
  File "/data8t_5/ljq/anaconda3/lib/python3.6/site-packages/graphtools/base.py", line 541, in diff_op
    return self.P
  File "/data8t_5/ljq/anaconda3/lib/python3.6/site-packages/graphtools/base.py", line 509, in P
    self._diff_op = normalize(self.kernel, 'l1', axis=1)
  File "/data8t_5/ljq/anaconda3/lib/python3.6/site-packages/
`
The data is human embryonic dataset of paper _Single-Cell RNA-Seq Reveals Lineage and X Chromosome Dynamics in Human Preimplantation Embryos_.
I just load the original data without log10 normalization.
The system is CentOS7 and the code is running with R 3.5.1 installed through Anaconda3.
All the related python packages have been successfully installed.
Could you help me out?

**Comment by scottgigante** [comment]
Hi @LiJiaqi96,

Do you mind running the following in a terminal and trying again?

```
pip install --user --upgrade graphtools
pip install --user --upgrade magic-impute
```

Thanks,
Scott

>

**Comment by LiJiaqi96** [comment]
Hi @scottgigante,

Thanks for your reply! Now it works!

As I have tried different devices and I found that it is necessary to install proper version of dependencies, such as numpy, spicy, scikit-learn magic.

Therefore, to solve the issue properly, one may need to first run the following commands in terminal:

```
pip uninstall numpy scipy scikit-learn magic
pip install --user --upgrade numpy scipy scikit-learn git+git://github.com/KrishnaswamyLab/MAGIC.git#subdirectory=python
```

Then run:

```
pip install --user --upgrade graphtools
pip install --user --upgrade magic-impute
```

Thanks for your quick reply!

**Comment by scottgigante** [comment]
For reference, `pip install magic-impute` will install all of its
dependencies and warn you if you have incompatible versions installed. So
if for whatever reason your dependencies are broken, the correct procedure
would be

```

pip uninstall numpy

pip uninstall scipy

pip uninstall scikit-learn

pip uninstall magic

pip uninstall magic-impute

pip uninstall graphtools

pip install --user magic-impute
```

Glad it's fixed!
