### ISSUE TITLE
Input and Output

### ISSUE THREAD

**Issue by Winnie09** [KrishnaswamyLab/MAGIC#151]
Dear author,

Thanks for developing the software! I have a few questions but did not find clear answer from your paper:

1. is the input a count matrix?
2. is the output a count matrix? Has it been normalized by library size, or log2-transformed?
3. I tried to use a raw count matrix as an input, but find negative values in output matrix?

Thanks!

**Comment by dvdijk** [comment]
1. yes. generally you want it to be library size normalized and log transformed
2. the output is a denoised version of the input
3. there can be small negative values in the output due to doing the imputation in pca space, which is done for speed. these negative values should be really small so they can be ignored or just set to zero

**Comment by PernilleYR** [comment]
Dear author, 

I have a related question regarding the input data. Should the genes be in rows or columns of data? 
In the tutorial the example data has genes as columns but going through the code and especially the function for Seurat object, magic is run on GetAssayData(SeuratObject, slot = "data") which is an object where the genes are in rows. 

Thank you very much for your time and thanks for this very nice software! 

Pernille

**Comment by scottgigante** [comment]
Hi @PernilleYR ,

Genes should be the columns of the data. In the Seurat function, MAGIC is run on `t(Seurat::GetAssayData(data, slot = 'data'))` which is the transpose of the Seurat matrix.

Hopefully that answers your questions. @Winnie09, if your question has been resolved please feel free to close this issue.

**Comment by Winnie09** [comment]
On the Cell paper (https://www.cell.com/action/showPdf?pii=S0092-8674%2818%2930724-4) page e2 section Overview of the MAGIC Algorithm, it says that the input should be count matrix (raw count matrix with integer values to my understanding) and preprocessing steps such as normalization is built in inside MAGIC. It seems that this is different from your previous comment that library size normalized and log transformed counts should be used as input. I wonder which one is the correct input to MAGIC. Thanks!

**Comment by scottgigante** [comment]
At the time of publication preprocessing was built into MAGIC, but since then we have realised this is limiting as users may want to use alternative preprocessing steps. As a result, the input should be preprocessed prior to input into MAGIC.
