### ISSUE TITLE
"Input matrix contains unexpressed genes" for AnnData object

### ISSUE THREAD

**Issue by milanmlft** [KrishnaswamyLab/MAGIC#152]
Hi,

I'm trying to run MAGIC on an AnnData object, but I always get the warning 
```
UserWarning: Input matrix contains unexpressed genes. Please remove them prior to running MAGIC.
  warnings.warn("Input matrix contains unexpressed genes. "
```
even though I am very sure that the data does not contain any non-expressed genes anymore...

I did some digging and I think there might be a mistake in the `has_empty_columns` function from [utils.py](https://github.com/KrishnaswamyLab/MAGIC/blob/master/python/magic/utils.py):
```
def has_empty_columns(data):
    try:
        return np.any(np.array(data.sum(0)) == 0)
    except AttributeError:
        if is_anndata(data):
            return np.any(np.array(data.X.sum(0)))
        else:
raise
```
in the case of an `AnnData` object, shouldn't it be `return np.any(np.array(data.X.sum(0)) == 0)` or am I missing something?

Thanks a lot for your help and the wonderful package!

**Comment by scottgigante** [comment]
Very good catch, thank you! I'll fix this in the next release.

**Comment by milanmlft** [comment]
Thanks a lot!
