### ISSUE TITLE
Regressing out the batch effect

### ISSUE THREAD

**Issue by bioguy2018** [KrishnaswamyLab/MAGIC#157]
Dear all,
I am wondering if I would like to regress out some source of variability within my data such as mitochondria percentage and n_counts, should it be done before imputation ? also if I subset my imputed data after an initial clustering, should I normalize my data again before looking for HVG or I can leave my data as it is!
I would appreciate it if someone give some information in this regard to me! 

Thanks

**Comment by scottgigante** [comment]
Sorry @bioguy2018 for the much delayed response. Here are my thoughts, if this question is still of interest to you.

1. Any technical effects (library size, batch effect, mitochondrial expression, cell cycle etc) should be handled prior to imputation. 
2. Any subsetting, even if informed by post-processed data, should be applied to raw data and then re-processed with just the subset of interest.
