### ISSUE TITLE
MAGIC for methylation data?

### ISSUE THREAD

**Issue by s18692001** [KrishnaswamyLab/MAGIC#164]
Hi there,

I have a gene by cell single cell DNA methylation data matrix. I'm looking for imputation tool that can help impute the missing value. I'm curious is MAGIC a suitable tool for methylation data?

**Comment by dvdijk** [comment]
yes, MAGIC should be able to impute single cell methylation data. You might want to do a different normalization compared to single cell RNA seq data though, but the other steps of the method should be the same

**Comment by dvdijk** [comment]
also, make sure your data is cells X genes, i.e. cells on the rows, as this is what magic expects
