### ISSUE TITLE
correcting for batch effects

### ISSUE THREAD

**Issue by mfrancesconi81** [KrishnaswamyLab/MAGIC#18]
Hi, 
is there a way of filter out batch effects before / during the imputation? i.e. if there is a component that explains a substantial part of the variance and it captures a batch effect how can I discard it from the imputation? 

Thanks, 

M.

**Comment by dvdijk** [comment]
if this is captured by a PCA component you can just run MAGIC on all other components, eg if its the first components you run MAGIC on 2:100 (or however many components you use)
are you using the python version?
tale a look at def magic() in MAGIC.py lines 10:39
after line 17 you can remove one of the components, such that compute_markov uses the components you want
