### ISSUE TITLE
TaskLogger error - Rmagic

### ISSUE THREAD

**Issue by tallulandrews** [KrishnaswamyLab/MAGIC#181]
**Describe the bug**
I can install and load Rmagic without errors, and I can import the "magic" python package without errors, but when I try to run the "magic" command I get the following error:
Error in py_call_impl(callable, dots$args, dots$keywords) :
  AttributeError: 'TaskLogger' object has no attribute 'task'

Detailed traceback:
  File "/software/team218/TA/my_condastuff/anaconda3/envs/magic/lib/python3.8/site-packages/magic_impute-2.0.3-py3.8.egg/magic/magic.py", line 699, in fit_transform
    with _logger.task("MAGIC"):

**System information:**
Python info:
Python 3.8.1 | packaged by conda-forge | (default, Jan  5 2020, 20:58:18)
[GCC 7.3.0] on linux
magic.version
<module 'magic.version' from '/software/team218/TA/my_condastuff/anaconda3/envs/magic/lib/python3.8/site-packages/magic_impute-2.0.3-py3.8.egg/magic/version.py'>

Output of `magic.__version__`:

```
If you are running MAGIC in R or Python, please run magic.__version__ and paste the results here.

You can do this with `python -c 'import magic; print(magic.__version__)'`
```

Output of `pd.show_versions()`:
INSTALLED VERSIONS
------------------
commit           : None
python           : 3.8.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-957.1.3.el7.x86_64
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.utf8
LOCALE           : en_GB.UTF-8

pandas           : 1.0.0rc0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 19.3.1
setuptools       : 45.0.0.post20200113
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : None
matplotlib       : 3.2.0rc1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
xlsxwriter       : None
numba            : None

<details>

```
If you are running MAGIC in R or Python, please run pd.show_versions() and paste the results here.

You can do this with `python -c 'import pandas as pd; pd.show_versions()'`
```

</details>

Output of `sessionInfo()`:
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS: /software/R-3.5.3/lib64/R/lib/libRblas.so
LAPACK: /software/R-3.5.3/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.utf8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.utf8        LC_COLLATE=en_GB.utf8
 [5] LC_MONETARY=en_GB.utf8    LC_MESSAGES=C
 [7] LC_PAPER=en_GB.utf8       LC_NAME=C
 [9] LC_ADDRESS=C              LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.utf8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] Rmagic_2.0.3  Matrix_1.2-17

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2       lattice_0.20-38  assertthat_0.2.1 crayon_1.3.4
 [5] dplyr_0.8.3      R6_2.4.0         grid_3.5.3       jsonlite_1.6
 [9] gtable_0.3.0     magrittr_1.5     scales_1.0.0     ggplot2_3.2.1
[13] pillar_1.4.2     rlang_0.4.0      lazyeval_0.2.2   reticulate_1.12
[17] tools_3.5.3      glue_1.3.1       purrr_0.3.2      munsell_0.5.0
[21] compiler_3.5.3   pkgconfig_2.0.2  colorspace_1.4-1 tidyselect_0.2.5
[25] tibble_2.1.3

<details>

```
If you are running MAGIC in R, please run sessionInfo() and paste the results here.

You can do this with `R -e 'library(Rmagic); sessionInfo()'`
```

</details>

Output of `reticulate::py_discover_config(required_module = "magic")`:

python:         /software/team218/TA/my_condastuff/anaconda3/envs/magic/bin/python
libpython:      /software/team218/TA/my_condastuff/anaconda3/envs/magic/lib/libpython3.8.so
pythonhome:     /software/team218/TA/my_condastuff/anaconda3/envs/magic:/software/team218/TA/my_condastuff/anaconda3/envs/magic
version:        3.8.1 | packaged by conda-forge | (default, Jan  5 2020, 20:58:18)  [GCC 7.3.0]
numpy:          /software/team218/TA/my_condastuff/anaconda3/envs/magic/lib/python3.8/site-packages/numpy-1.18.1-py3.8-linux-x86_64.egg/numpy
numpy_version:  1.18.1
magic:          /software/team218/TA/my_condastuff/anaconda3/envs/magic/lib/python3.8/site-packages/magic_impute-2.0.3-py3.8.egg/magic

python versions found:
 /software/team218/TA/my_condastuff/anaconda3/envs/magic/bin/python
 /usr/bin/python
 /usr/bin/python3

<details>

```
If you are running MAGIC in R, please run `reticulate::py_discover_config(required_module = "magic")` and paste the results here.
You can do this with `R -e 'reticulate::py_discover_config(required_module = "magic")'`
```

</details>

**Additional context**

**Comment by scottgigante** [comment]
It looks like you have the wrong version on tasklogger. Can you please run the following?
```
python -c 'import magic; print(magic.__version__)'
python -c 'import tasklogger; print(tasklogger.__version__)'
```
If tasklogger is less than version 1.0.0, you can resolve the issue with
```
pip install --user --upgrade tasklogger
```

**Comment by tallulandrews** [comment]
Thanks I couldn't figure out which package was the one that was out of
date, that has resolved the issue.

Best,
Tallulah

**Comment by scottgigante** [comment]
You're welcome!
