### ISSUE TITLE
Which slot is Rmagic pulling from a Seurat object?

### ISSUE THREAD

**Issue by dagarfield** [KrishnaswamyLab/MAGIC#182]
Hello,

Hopefully an easy question, but when running magic (Rmagic) on a Seurat object, which slot is used? Is it `counts`, `data`, or `scale.data`?

Thanks

**Comment by scottgigante** [comment]
For MAGIC we used the normalized data, so the `data` slot.

Seurat v2: https://github.com/KrishnaswamyLab/MAGIC/blob/master/Rmagic/R/magic.R#L267

Seurat v3: https://github.com/KrishnaswamyLab/MAGIC/blob/master/Rmagic/R/magic.R#L332

**Comment by dagarfield** [comment]
Oh, fantastic. Thanks. And presumably for calculating PCAs, you're then pulling from the scale.data slot? (or even from the PCA stored in the Seurat assay?)

**Comment by scottgigante** [comment]
No worries. Actually re: PCA, we compute this on the normalized data even if it is computed elsewhere -- PCA is not the biggest computational bottleneck and it's easier just to pull one thing from the Seurat object and then run the rest of our algorithm standalone.

**Comment by dagarfield** [comment]
Ah! Since you’d included the ScaleData step in some of the tutorials, I’d
assumed this came into play. But it’s all much clearer now. Thanks!

**Comment by scottgigante** [comment]
This might be my inexperience with Seurat showing through :) From memory, I believe ScaleData was necessary in order to do some of the later steps in the tutorial, but not for MAGIC.

**Comment by dagarfield** [comment]
Solid. We can consider this closed. Next step....a wrapper for phateR.....

**Comment by scottgigante** [comment]
@dagarfield it's not officially supported but if you install from my fork, I have a wrapper. Read more: https://github.com/satijalab/seurat/pull/1172#issuecomment-564782167
