### ISSUE TITLE
ligand-receptor pair analysis

### ISSUE THREAD

**Issue by yaolutian** [KrishnaswamyLab/MAGIC#184]
Hi, 
Thanks for this beautiful package.

I am wondering if it is suitable to use the MAGIC_RNA assay for ligand receptor pair analysis, for example using the CellphoneDB package.

Thanks,
Lutian

**Comment by scottgigante** [comment]
I see no reason why not! In fact in the MAGIC paper, the authors do a lot of gene-gene relationship analysis and show that this works better with MAGIC than without in certain contexts.

**Comment by yaolutian** [comment]
> I see no reason why not! In fact in the MAGIC paper, the authors do a lot of gene-gene relationship analysis and show that this works better with MAGIC than without in certain contexts.

Great! Thanks a lot!
