### ISSUE TITLE
is here a potential bug?

### ISSUE THREAD

**Issue by dustincys** [KrishnaswamyLab/MAGIC#185]
Hi, @scottgigante 

here:
https://github.com/KrishnaswamyLab/MAGIC/blob/master/python/magic/magic.py#L830

is it right 
` t_opt = i `

instead of 
`t_opt = i  + 1` ?

**Comment by scottgigante** [comment]
Thanks for checking! This is actually as designed -- the heuristic stops with `t` one higher than where the error drops below the threshold. This doesn't break the loop, so when we set `t_opt` it just runs the loop once more.

**Comment by dustincys** [comment]
Thank you for quick reply. I don't think that will runs the loop **once** more.

In the "last" loop,  at the beginning, while[ here](https://github.com/KrishnaswamyLab/MAGIC/blob/master/python/magic/magic.py#L816), i == t_opt -1,  next, after [here](https://github.com/KrishnaswamyLab/MAGIC/blob/master/python/magic/magic.py#L818) i == t_opt, **if error < threshold** , then [here](https://github.com/KrishnaswamyLab/MAGIC/blob/master/python/magic/magic.py#L830), i == t_opt-1 **again**.

**Comment by scottgigante** [comment]
Thanks for checking! Line 829's `and t_opt is None` ensures that line 830 won't be run more than once, I believe.

**Comment by dustincys** [comment]
Thank you @scottgigante , that's right.
