### ISSUE TITLE
kNN-DREMI

### ISSUE THREAD

**Issue by kevin199011** [KrishnaswamyLab/MAGIC#20]
Hi, is it possible to add about how to calculate kNN-DREMI in the tutorial? Thank you!

**Comment by dvdijk** [comment]
We will add kNN-DREMI in the coming weeks. Sorry for the delay.

**Comment by dpcook** [comment]
Hey David and Pooja,

Just wondering if there's been any update on including a kNN-DREMI script/function?

**Comment by dvdijk** [comment]
We'll add this very soon -- next month. First Matlab, then Python. I think
it will take a bit longer until we have it in R.

**Comment by dpcook** [comment]
Sounds good! I appreciate it.

**Comment by adddddn** [comment]
Hey, any updated on kNN-DREMI? Thanks!

**Comment by dvdijk** [comment]
We're adding this soon. Sorry for the delay!

**Comment by dvdijk** [comment]
We are still working on this but we expect to release the code very soon.
Sorry its not available yet!

**Comment by dburkhardt** [comment]
Hi all, kNN-DREMI has been released in python as part of our package scprep in version 0.7 <https://github.com/KrishnaswamyLab/scprep>. You can find the method at `scprep.stats.knnDREMI()`. The default parameters are the ones used in the MAGIC paper.
