### ISSUE TITLE
Introducing artificial dropout issue

### ISSUE THREAD

**Issue by radio1988** [KrishnaswamyLab/MAGIC#48]
For Fig.8 MAGIC paper, it's stated that random values sampled from an exponential distribution were subtracted from expression values, such that 0%, 60%, 80%, and 90% of the values are 0 after down-sampling. In Fig.1, it's stated that 'artificial dropout' were introduced by randomly setting 80% of the values to 0. 
Which method is more appropriate to mimic the 'dropout' in real RNA-seq data? How is the method in Fig. 8 implemented? Will it be appropriate if we set up a threshold and set any expression value lower than the threshold to 0?
Thanks!

**Comment by dvdijk** [comment]
Everywhere in the paper (including Fig.1 and 8) where simulate dropout we
don't just set a fraction of the values to zero, but we randomly subsample
molecules by subtracting values randomly sampled from an exponential
distribution, thus *all* entries in the matrix are reduced, as a result
some become zero. This is the right way to simulate dropout as dropout is
not just setting some values to zero but it affects every entry in the
matrix.

**Comment by audreyqyfu** [comment]
Thanks, David.  I'm also interested in the simulation setup.  Do I understand correctly that this exponential distribution is *independent* of gene expression?  In other words, a gene may be highly expressed, but the number to subtract can be small, whereas a lowly expressed gene may be hit with a large value from this exponential distribution?   

Thanks,
Audrey

**Comment by radio1988** [comment]
Thanks, David. Audrey's comment is interesting, too. If the sampling from exponential distribution is independent from the expression value being subtracted, would it be more 'realistic', if we re-sample reads from each cell? E.g. Cell-i has 10M reads as ground truth(very few zeros),  we re-sample 0.5M reads from it, as a result, lots of zeros are introduced. In terms of 're-sample', I meant something similar to bootstrap, except only taking 0.5M reads rather than 10M reads out of the re-sampling with replacement process.

**Comment by dvdijk** [comment]
What you can do, and this is something we had done but gave very similar
results, is actually subsample the molecules.  don't think you want to
subsample reads bc, unless you want to test how well it can recover low
read samples.

**Comment by dvdijk** [comment]
that is correct. However, making it dependent on the mean gave very similar
results.
you could actually subsample the molecules to be even more realistic.

**Comment by audreyqyfu** [comment]
glad to hear that the exponential distribution dependent or independent of gene expression gives similar results.  I guess it means that magic is robust to the potentially highly random process of dropout.

**Comment by dvdijk** [comment]
In fact, having the dropout be greater on highly expressed genes versus
lowly expressed genes should make things easier for magic since it will
maintain more genes (i.e. Not remove as many lowly expressed genes)
