### ISSUE TITLE
Log-transformation before MAGIC

### ISSUE THREAD

**Issue by fbrundu** [KrishnaswamyLab/MAGIC#69]
I noticed that log-transformation before MAGIC shrinks the explained variance of the principal components.

Using

    scdata.plot_pca_variance_explained(n_components=n)

was useful to understand how to set up the number of pc parameter in MAGIC. However, with log-transformed data it is not clear which value to choose for this parameter since cumulative explained variance for the first 100 components usually reaches only 10-25% of total explained variance.

I am aware that I shouldn't use rescaling (by setting it to 0) for log-transformed data. However, it seems that log-transformed data can be used with MAGIC. Is it correct and, how to choose a cutoff for number of principal components?

[Attached question from stackexchange](https://stats.stackexchange.com/q/319794/29911).

**Comment by dvdijk** [comment]
yes, you can use MAGIC on log-transformed data. You can use MAGIC after any
transformation.
The number of PC components to use really depends on your data. This is not
something that's specific to MAGIC, but is a standard preprocessing step
for any single cell analysis. Technically MAGIC doesn't require PCA,
however, it speeds up the computation of the distance matrix. So its better
to pick too many than too few components. 100 should be fine for almost all
datasets.
