### ISSUE TITLE
How to reproduce Figure 7A of original paper to estimate optimal values for t and ka

### ISSUE THREAD

**Issue by fbrundu** [KrishnaswamyLab/MAGIC#70]
I am trying to understand how to set parameters for `t` and `ka` since I noticed that changing them in my case severely affects how the values are imputed.
Does MAGIC have a method to reproduce a plot similar to the the Figure 7A?

> Figure 7: Finding the optimal diffusion time (t) using intrinsic dimensionality estimation. A) Graph shows intrinsic dimensionality (as measured by correlation dimension) computed on EMT data for different amounts of diffusion time (t) for three values of adaptive kernel (𝑘𝑎 = 4, 10, 30). The peak values suggest optimal diffusion times that restore maximal dimensionality (information) to the data.

Thanks,
Francesco

**Comment by dvdijk** [comment]
Hi Francesco,

We're about to publish a method for selecting t on github. This
should happen this month.
As for ka, you want to set it as small as possible. Start with ka=3.

David

**Comment by adddddn** [comment]
David, do you have any updates on when this will be published? In the meantime, do you have any advice for choosing parameters?

For example, if I vary 't' and 'ka', then use an R package to calculate correlation dimension (e.g. fractal), would this be sufficient to produce Fig 7?

**Comment by dvdijk** [comment]
Yeah, we have developed a new method for finding the optimal t.
See: compute_optimal_t.m for Matlab. We also have it for R and Python.
We're in the process of adding optimal t calculation to the tutorials,
though the functions should be pretty straightforward to use.
Let us know if you have problems running them

**Comment by adddddn** [comment]
Thanks! To tune the parameters, I am planning on running magic with varying ka (between 4 and 30) and the optimal t calculation. I was then going to plot the correlation dimension against ka. Is this what you would recommend?

**Comment by dvdijk** [comment]
I wouldn't use correlation dimension at all. I would start with ka=4 and if
that doesn't work well try bigger up to 10, no need for bigger I think.
Optimal t will give you the t

**Comment by adddddn** [comment]
Thanks for the quick response. Sorry if this is a dumb question, but how do I know if it works well? Is there something you do to evaluate each imputation?

**Comment by adddddn** [comment]
Quick update: I tried running magic with ka=4 and ka=10 (and optimal t calculation). To evaluate the results, I re-calculated the TSNEs (see attached files). All of the original clusters were well-supported by canonical markers from the literature. However, the imputation seems to have blurred (and in some cases, obliterated) the cluster distinctions. Any ideas what might be going wrong?

Methods: I am running magic on the TPM matrix (*not* scaled/log-transformed). I am using 20 PCs, which has worked for this dataset previously. Otherwise, I am using the default parameters found in the MAGIC.py script (k=30, t=None, epsilon=1, r=99, etc). The optimal ts seemed reasonable. For ka=4, the optimal t was 5. For ka=10, the optimal t was . After running magic, I treat the imputed data as a TPM matrix and I run a standard pipeline to get the tSNE (i.e. variable gene selection, PCA on scaled log(TPM+1), tSNE). I have also tried using my original set of variable genes.

These new TSNEs are not necessarily incorrect, but they do not align with the established markers as well. So I'm curious if you have encountered similar problems, and whether you have any advice? Thank you.

Original
![magic old tsne](https://user-images.githubusercontent.com/36550288/36347547-9d2bc2fe-1427-11e8-90d7-04649d10d9c0.png)

ka=4
![magic ka4 tsne](https://user-images.githubusercontent.com/36550288/36347549-9d4c524e-1427-11e8-8bd2-d4ba42ca49ff.png)

ka=10
![magic ka10 tsne](https://user-images.githubusercontent.com/36550288/36347548-9d380c12-1427-11e8-91b0-be2d732a76fb.png)

**Comment by dvdijk** [comment]
I would not recommend running tSNE after MAGIC (or in general) since
tSNE destroys continuous structure in the data and forces clusters.
You can do PCA after MAGIC, or use our other tool called PHATE (on the raw
data).

Do you library size normalize your data prior to running magic?

**Comment by adddddn** [comment]
I have tried with and without library size normalization. I'm not sure what assumption in tSNE forces clusters, unless you are referring to the graph clustering step? I think tSNE simply embeds the high dimensional data in a 2D space, where similar points are close together. If the imputation is working correctly, shouldn't similar cell types still be positioned close together in a tSNE plot?

However, I have no particular affinity for tSNE plots :) Is there anything else you suggest for validating the imputed data? For example, do you start looking at gene-gene correlations to see if they make sense? Even if there aren't any hard metrics you are using at the moment, if you can just give me a sense for what you tend to look at, it would be tremendously helpful. Thanks! :)

**Comment by dpcook** [comment]
You could plot cluster ID (pre-magic) vs. marker expression (pre/post-MAGIC). Should be tighter relationships post-MAGIC. Could also re-cluster the imputed data and see if it pulls out canonical cell types (based on marker expression). Validating gene-gene relationships is also helpful. These are probably the best ways to validate the data.

For visualization, as David said, tSNE falls apart post-MAGIC. Check simple PCA/Diffusion Map/PHATE embedding. If you're not used to looking at them, just a heads up that they will look different than tSNE plots (less circular patterns, more smears/streak patterns--that's normal).

**Comment by dvdijk** [comment]
also, see here:
https://www.biorxiv.org/content/early/2017/12/01/120378.article-info
for some examples where tsne fails

I recommend doing library size normalization at all times

**Comment by adddddn** [comment]
dpcook and dvdijk, thanks for the links and suggestions. Will take a look and report back :)

**Comment by adddddn** [comment]
I have looked at the references, but still have a few questions.

1) I understand that tSNE might not be _optimal_ for data visualization, but I don't think it should "break down" post-MAGIC. tSNE has been used for many datasets across many disciplines and even though it doesn't reflect global structure, it should capture local similarities. As expected, the MAGIC-imputed tSNE is congruent with the results from graph clustering. (This is not to say that other methods such as diffusion maps and PHATE are not better suited to the data).

2) Following the suggestion of @dpcook I re-clustered the MAGIC-imputed data. The results are a little mixed. The new clusters do not align as well with the established markers and I lose some important cell types. However, MAGIC does seem to reveal interesting variation in some groups (for example, separating T cells by patterns of cytokine expression). I'm trying to understand out how much I can trust these results. I also notice the following:

- When I run DE tests on the clusters, I find hundreds of genes that can discriminate each cluster with AUC > 0.9, which seems quite high?
- When I do gene-gene correlations across the entire dataset, I find many **Spearman** correlations that exceed 0.90 (across thousands of cells). These examples make biological sense, but 0.90 seems very high?
- MAGIC reveals new clusters in my data. When I calculate the top DE genes, then look at these in the original data (i.e. the non-imputed data), they are very lowly expressed in that cell type - and some are completely absent. For example, CTLA4 is a positive marker for cell type A in the MAGIC data with AUC > 0.9. But when I look at the original data, it is completely absent from all 2000 cells in cell type A.

I would like to get your opinion on this, but to me, it seems that MAGIC is being overly aggressive? It is blurring cluster distinctions, making "discrete" states (i.e. terminally differentiated cells) much more continuous, inducing strong gene-gene correlations in the data, and amplifying the expression of very lowly expressed genes to high levels.

However, like I said, the gene-gene correlations make a lot of sense, and there are some interesting sub-structures in the data. I just don't know how much I can trust this. If you have any thoughts on this, I would be glad to hear them. Thanks!

**Comment by adddddn** [comment]
Just to follow up, I'm curious if these observations are consistent with what you have observed with MAGIC? Or perhaps they point to obvious flaws in my analysis? For example, maybe these results suggest that my parameter selection is flawed, or perhaps my dataset is particularly challenging for the method? This is really my first time using MAGIC, so I have no idea what to expect. Do you also find gene-gene correlations with Spearman's rho > .9? Overall, I'm not sure how aggressive the imputation should be when it's working correctly. Thanks again.
