### ISSUE TITLE
request: port to bioconda

### ISSUE THREAD

**Issue by mheskett** [KrishnaswamyLab/MAGIC#73]
conda is an excellent package manager for python3 and seems like is gaining in popularity. Could you create a conda recipe for magic?

**Comment by cimbusch** [comment]
I totally would appreciate that as well. I do not have root access to execute the global installation command such as "sudo -H pip3 install .", it should be somehow possible to install it into user space. Usually I use bioconda for that.

The R installation worked but aborted with the error "Error: $ operator is invalid for atomic vectors"

**Comment by pkathail** [comment]
Will look into adding this -- thanks for the suggestion!

**Comment by adddddn** [comment]
@cimbusch, there are a few ways to install locally with pip3, e.g.

pip3 install --user $USER .
pip3 install --install-option='--prefix=$HOME' .

(replace $USER and $HOME to change install location)

**Comment by scottgigante** [comment]
MAGIC has been added to PyPi as `magic-impute` - I don't think we have any short term plans of adding to conda since Anaconda's native `pip` support is pretty good, so I'm closing this for now. Anyone who is interested is welcome to create a recipe to add to bioconda or conda-forge if they like.
