### ISSUE TITLE
divide by zero error if matrix contains any genes with zero total counts

### ISSUE THREAD

**Issue by mheskett** [KrishnaswamyLab/MAGIC#74]
these should just be automatically filtered out, not cause an error.
![dictation_status_window_and_test_magic](https://user-images.githubusercontent.com/11022774/34799305-2cefca16-f614-11e7-8fd0-1e81eec023f8.png)

**Comment by scottgigante** [comment]
We prefer not to filter genes out automatically as this might cause problems with the user's matrix indexing. However, as of v1.1, MAGIC now throws a warning if an unexpressed gene is included in the input.
