### ISSUE TITLE
Following MAGIC Notebook Tutorial

### ISSUE THREAD

**Issue by mealbahrani** [KrishnaswamyLab/magic#75]
Hello,
I am fairly new to scRNA-seq analysis, but I found your tool has great potential to resolve the overwhelming zero values in our lab's data set.

Could you please provide more description on the [Data preprocessing](https://github.com/pkathail/magic/blob/develop/notebooks/Magic_single_cell_RNAseq.ipynb) section in the notebook tutorial?  I am not sure what the parameters (`CELL_MIN`, `CELL_MAX`, `GENE_NONZERO`, `GENE_MOLECULES`) signify, and how to set them appropriately to impute zero values in the data set.

I appreciate your help,
Mustafa

**Comment by pkathail** [comment]
Hi Mustafa,

I believe the discussion in Issue #66 is helpful for how to set the parameters you mentioned.
