### ISSUE TITLE
remove "MAGIC " from output

### ISSUE THREAD

**Issue by mheskett** [KrishnaswamyLab/MAGIC#83]
currently writing scdata.magic.data as a text file results with "MAGIC " is prefixed to all the genes which makes this file incompatible with further analysis requiring standard gene names. Not having a proper method to export the data makes this package hard to use outside of running the examples

**Comment by pkathail** [comment]
You can save the MAGIC-ed version of the data to a csv file without "MAGIC" prefixed to all the genes with `scdata.magic.to_csv('filename')`
