### ISSUE TITLE
filtering step adds cells?

### ISSUE THREAD

**Issue by spgarcia** [KrishnaswamyLab/MAGIC#87]
Hi,
I'm using MAGIC on the Paul et al. 2015 data and following your notebook for the analysis. However, the filter_scseq_data step is adding cells to my data matrix. Any idea why this is happening? 
Thanks,
Sara

**Comment by dvdijk** [comment]
Not sure why this is happening, but the Paul et al. 2015 data might not
need filtering since its already filtered
