### ISSUE TITLE
Weight matrix not necessarily square, ERROR 

### ISSUE THREAD

**Issue by PernilleYR** [KrishnaswamyLab/magic#89]
In the R code the matrix W is a sparse Matrix indicating the k nearest neigbhour of each cells. It is possible that some cells are never one of the k nearest neighbour of any other cells, leading to a column full of 0 in W (or without any info about it in the case of a sparse matrix). In my case for example, the last cells of my matrix never occured to be one of the k closest neighbour of any other cells (I had to increase k a lot otherwise) leading in a matrix that was not square and it was therefore impossible to do the step "Symmetrize distances" by doing the sum of W and its transpose matrix. 

I wrote a bit of code to simply complete the matrix W with columns of 0 in case the matrix is not square as you can see follow: 
 
N = nrow(data) # Number of cells
#[...]
if (epsilon > 0) {
    W <- Matrix::sparseMatrix(i, j, x=s)
  } else {
    W <- Matrix::sparseMatrix(i, j, x=1) # unweighted kNN graph
  }
  print('Symmetrize distances')
  W <- as.matrix(W)
  
  #---------------------------------ADDED CODE 
    dim = dim(W)[2]
    if( dim != N ){
      m <- matrix(data=rep(0, (N-dim)*N), nrow=N, ncol=(N - dim))
      W = cbind(W, m)
    }
  #---------------------------------END  
      
  W <- W + t(W)

**Comment by nganvu** [comment]
Fixed. Thank you for the suggestion!
