### ISSUE TITLE
How to log transform the data

### ISSUE THREAD

**Issue by strawberrymeow** [KrishnaswamyLab/magic#90]
Hi there,

Thank you for sharing the code to the public and managing issues from us!

I was using the linear data as input in the magic tutorial notebook. One of my figures looked weird and Dr. David Vandijk kindly suggested me to log transform the data using (data = log(data + 0.1). However, I don't know much coding and not sure how to achieve that... Would you please help out?

Thank you again!

Wei

**Comment by pkathail** [comment]
Hi Wei,

You can first load your data using the MAGIC package. For a csv file this can be done with the command: `scdata = magic.mg.SCData.from_csv(file_name, data_type='sc-seq')`. Loading data in the way will automatically perform median library-size normalization. To prevent this, you can use the command: `scdata = magic.mg.SCData.from_csv(file_name, data_type='sc-seq', normalize=False)`

Then, to log-transform the data with a pseudocount of 0.1, you can use the command: `scdata.log_transform_scseq_data(pseudocount=0.1)`

Hope this helps!
