### ISSUE TITLE
module 'magic' has no attribute 'mg'

### ISSUE THREAD

**Issue by cynthiazhou1005** [KrishnaswamyLab/MAGIC#91]
Hi,

I recently reinstalled magic and now it wouldn't allow me to use my previous notebook as it has been saying "module 'magic' has no attribute 'mg' " 
Any idea?

Thanks!

**Comment by pkathail** [comment]
What commands did you use to uninstall and reinstall?

**Comment by danieldager** [comment]
Hi Cynthia,

This problem was resolved with the release of MAGIC v1.0. Uninstall your current version of MAGIC and reinstall per the directions of the new README. I'm closing this for now; please feel free to open a new issue if you still have problems!

Best,
Daniel
