### ISSUE TITLE
Optimal parameter choice

### ISSUE THREAD

**Issue by Nak0r** [KrishnaswamyLab/magic#95]
Hi,

I am currently working on a comparison paper about imputation algorithms and I would like to include MAGIC. I get very different results when I try different parameter set, do you have any recommendation for their tuning, and especially:
- Should I use the raw count as input?
- How many PCA components should I use (or which range)
- How many genes to process the optimal t?
Thank you!

**Comment by dvdijk** [comment]
Hi,

You should do library size normalization and likely also log transformation
Plot the eigenvalues, you'll see how many PCA components to pick:
![image](https://user-images.githubusercontent.com/73651/38070496-3c43b35c-32ea-11e8-96a6-3853e37e53c1.png)
Here you would pick something like 50 components

In general you probably wont pick more than 100, so 100 should be safe in any case

500 or more genes to compute optimal t. More genes is better but will be slower. Pick 1000 if you want to be safe.

-David

**Comment by Nak0r** [comment]
Thanks! You're right, it's better with log values. However, I get some kind of warning when I log transform:
"Rescaling should not be performed on log-transformed (or other negative) values. Imputed data returned unscaled.",
which made me hesitate at first whether I should do this transformation.

**Comment by dvdijk** [comment]
its fine, its just that it wont rescale but rescaling is mostly esthetic
anyway -- its scaling the values to the original range, you dont need that
