### ISSUE TITLE
Error from R version's MAGIC

### ISSUE THREAD

**Issue by WT215** [KrishnaswamyLab/MAGIC#96]
Hi,

The R outputs an error:
```
> MAGIC_H1 <- run_magic(cbind(H1_p24,H1_p96)[whichg_H1,])
[1] "Library size normalization"
[1] "PCA"
[1] "Computing distances"
[1] "Adapting sigma"
[1] "Symmetrize distances"
[1] "Computing kernel"
[1] "Markov normalization"
[1] "Diffusing"
Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace = FALSE'
```

The version of R is 3.4.4. I can provide the data if needed.

Cheers,
Wenhao

**Comment by WT215** [comment]
When I run
`MAGIC_H1 <- run_magic(cbind(H1_p24,H1_p96)[whichg_H1,], t=6, rescale_percent=0.99)`
Then it is ok.

**Comment by WT215** [comment]
I am afraid that the same error appears when I ran MAGIC on another dataset. The dataset can be downloaded from my github: [https://github.com/WT215/Raw_data](url)

```
load("~/RAW_DATA.RData")
MAGIC_islam <- run_magic(DAT_Jaakkola)
```
```

The output error is:

> MAGIC_output <- run_magic(DAT_Jaakkola)
[1] "Library size normalization"
[1] "PCA"
[1] "Computing distances"
[1] "Adapting sigma"
[1] "Symmetrize distances"
[1] "Computing kernel"
[1] "Markov normalization"
[1] "Diffusing"
Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace
= FALSE' 
``` 

Cheers,
Wenhao

**Comment by nganvu** [comment]
I found an edge case in the code to automatically compute t when t is not specified and fixed it. Could you try again? Thanks.

**Comment by WT215** [comment]
Hi @nganvu 

Thank you for your help!

I updated the package and rerun that code, but got another error:

```
> MAGIC_islam <- run_magic(DAT_Jaakkola)
[1] "Library size normalization"
[1] "PCA"
[1] "Computing distances"
[1] "Adapting sigma"
[1] "Symmetrize distances"
[1] "Computing kernel"
[1] "Markov normalization"
[1] "Diffusing"
[1] "n_genes too large, capping n_genes at maximum possible number of genes"
[1] "Computing optimal t"
************
[1] "Optimal t = Inf"
Error in plot.window(...) : need finite 'ylim' values
In addition: Warning messages:
1: In min(which(r2_vec < 0.05)) :
  no non-missing arguments to min; returning Inf
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf
```
Cheers,
Wenhao

**Comment by nganvu** [comment]
Code is updated! Can you try once again? Thank you!

**Comment by WT215** [comment]
Hi @nganvu,

I updated the package and rerun the code but still got the same error:
```

> MAGIC_islam <- run_magic(DAT_Jaakkola)
[1] "Library size normalization"
[1] "PCA"
[1] "Computing distances"
[1] "Adapting sigma"
[1] "Symmetrize distances"
[1] "Computing kernel"
[1] "Markov normalization"
[1] "Diffusing"
[1] "Computing optimal t"
********************************
[1] "Optimal t = Inf"
Error in plot.window(...) : need finite 'ylim' values
In addition: Warning messages:
1: In min(which(r2_vec < 0.05)) :
  no non-missing arguments to min; returning Inf
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf
```
This is a non-UMI data, could this be a reason?

Cheers,
Wenhao

**Comment by nganvu** [comment]
According to the error, this just means the data is not 'diffused' enough. We currently have the number of maximum steps to diffuse the data at 32, which works other datasets so far. I will edit the code so that the maximum steps to diffuse the data is not capped at some fixed value but rather increased as needed. I'll let you know when the code is updated again.

**Comment by nganvu** [comment]
For now, I suggest that you specify a `t` in your `run_magic()` call, so that `t` doesn't have to be computed automatically. I suggest a value that's at least 32.

**Comment by WT215** [comment]
Ok I see! Thanks a lot!

**Comment by dvdijk** [comment]
what kind of normalizations do you on your data?
I would start with t=6 and then increase if necessary

**Comment by WT215** [comment]
Hi @dvdijk , it is a non UMI based data from Islam et al. 2011 where there are around 6000 genes and 92 cells after filtering. I will fix the parameter t and try again.

**Comment by dvdijk** [comment]
92 cells is very little. Probably too few to do magic on.. My guess is that
this is why optimal t didnt work

**Comment by dvdijk** [comment]
aren't you able to find more recent datasets of the same system? whats the
biological system?

**Comment by dvdijk** [comment]
Alon Klein has generated mESC single cell data and maybe 10x has some too
https://support.10xgenomics.com/single-cell-gene-expression/datasets

if you really want to run magic on these 92 cells try a low k:
k = 3, ka=3 (or 4 if that doesnt work)

**Comment by WT215** [comment]
Great! I will have a try. Thank you very much! @dvdijk
