### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by radio1988** [KrishnaswamyLab/MAGIC#97]
I downloaded the 0.1 version of python magic, uninstalled old version, and installed the new version again with `pip3 install .`

however, when I 
```
import magic
print(magic.__version__)
```

it says 0.0

which version am I using ?
Thanks!

**Comment by pkathail** [comment]
Hi, I apologize for the late response. The version number was not in accord with the release, but that is in fact the 0.1 version of MAGIC. I have now updated it accordingly

**Comment by radio1988** [comment]
Thanks pkathail!
