### ISSUE TITLE
MAGIC recommended settings

### ISSUE THREAD

**Issue by ghost** [KrishnaswamyLab/MAGIC#98]
Hi! Thanks for your work on MAGIC. I had a few quick questions.

1) Do you recommend running on log-transformed data? Or just the normalized counts?

2) With ka=4 and optimal t, MAGIC is still pretty aggressive (almost all of my genes have correlation > 0.95). Any recommendations? Should I manually lower t?

Thanks!

**Comment by dvdijk** [comment]
1. log normalized (e.g. log(x+0.1)) is almost always better, on top of the
library size normalized values
2. what is the optimal t? what is your data? how many cells? pca?

**Comment by adnbps** [comment]
5k cells, 20k genes

ka = 4
Optimal t = 6
20 PCs
Default for all other settings

Thanks!

**Comment by dvdijk** [comment]
so you do library size normalization? I would do log after that
you can use more PCs, like 100.

**Comment by dvdijk** [comment]
btw, with these settings it doesnt make sense that all genes have
correlation > 0.95
maybe library size normalization + log will help

**Comment by adnbps** [comment]
Thanks, I will try that. I am doing library size normalization followed by log transform. The PCs are only used for the distance calculation, correct?

I also saw someone mention that I shouldn't use the rescale option with the log transform. Is this correct? I am running it with rescale_percent=99. Thanks again.

**Comment by JurijsNazarovs** [comment]
I found in their code:

#' @param rescale_percent To which percentile should the data be re-scaled.
--
17 | #' Note: Do not set this higher than 0 if you also want to log-transform.

**Comment by danieldager** [comment]
Hi all, 

Just wanted to notify you that rescaling has been removed with the release of MAGIC v1.0 last week. 

Best,
Daniel
