### ISSUE TITLE
R, Python, MATLAB?

### ISSUE THREAD

**Issue by chlee-tabin** [KrishnaswamyLab/MAGIC#99]
Hi,

This is a super silly question but which of the three implementations (R, Python, MATLAB) is most up-to-date? I want to try out MAGIC and I can work on either of the three (slightly my pipeline and processes are mostly on R), but wondering whether there are any differences in terms of speed or particular features that are only implemented in one versus the other.

Thank you!

**Comment by nganvu** [comment]
We try to keep the implementation the same across all languages.

**Comment by danieldager** [comment]
Hi chlee,

With the release of v1.0 last week, MAGIC will now run substantially faster on all three languages. It should be noted that the R implementation essentially acts as a wrapper for the Python code, so their execution times will be nearly identical. If you're most comfortable with R, then I would recommend you do that.

Best,
Daniel
